version: '2'
# deployment docker compose for flair-registry
services:
    flair-registry:
        container_name: "flair-registry"
        labels:
            purpose: Flair config server and service discovery
        image: flairbi/flair-registry:${TAG}
        volumes:
        - /home/vizcentric/Documents/flair-configuration:/flair-configuration
        environment:
        - JHIPSTER_SLEEP=0
        - SPRING_PROFILES_ACTIVE=prod
        - BITBUCKET_URI=https://github.com/viz-centric/flair-config.git
        - BITBUCKET_USER=${BITBUCKET_USER}
        - BITBUCKET_PASS=${BITBUCKET_PASS}
        networks:
            - flair-network

networks:
    flair-network:
        external:
            name: flair-network
