version: '2'
# deployment docker compose for flair-registry
services:
    flair-registry:
        container_name: "staging-flair-registry"
        labels:
            purpose: Flair config server and service discovery
            environment: staging
            traefik.frontend.rule: "PathPrefixStrip: /flair-registry-staging"
            traefik.enable: true
            traefik.backend: flair-registry
            traefik.docker.network: traefik

        image: ${DOCKER_REGISTRY_URL}/flair-registry:latest-${GIT_LOCAL_BRANCH}
        volumes:
        - /home/vizcentric/Documents/flair-configuration:/flair-configuration
        environment:
        - JHIPSTER_SLEEP=0
        - SPRING_PROFILES_ACTIVE=prod
        - BITBUCKET_URI=${BITBUCKET_URI}
        - BITBUCKET_USER=${BITBUCKET_USER}
        - BITBUCKET_PASS=${BITBUCKET_PASS}
        ports:
        - 8761:8761
        logging:
            driver: "fluentd"
            options:
                fluentd-address: localhost:24224
                tag: flair-registry-staging
        networks:
            - traefik
            - stag

networks:
    stag:
        external:
            name: staging
    traefik:
        external:
            name: traefik
